### ISSUE TITLE
Issue on gmake

### ISSUE THREAD

**Issue by priosoft** [sitemule/sitemule.github.io#1]
First :  Error was noxDB folder empty. Revolved on copying file manually

Second : Error was  src/datagen.c not found in src folder

system "CRTCMOD MODULE(ILEASTIC/datagen) SRCSTMF('src/datagen.c') OPTIMIZE(10) ENUM(*INT) TERASPACE(*YES) STGMDL(*INHERIT) SYSIFCOPT(*IFSIO) INCDIR('/QIBM/include' 'headers/' 'headers/ext/' ) DBGVIEW(*ALL) DEFINE() TGTCCSID(*JOB) TGTRLS(V7R2M0)"
CZS0601: Il modulo DATAGEN non viene creato in quanto si sono verificati errori di istruzione.
CZM0613: La compilazione ha avuto esito negativo.
gmake[1]: *** [makefile:64: datagen.c] Error 255
gmake[1]: Leaving directory '/prj/ILEastic/noxDB'
gmake: *** [makefile:53: noxDB] Error 2

**Comment by NielsLiisberg** [comment]
My guess is you need to change the "makefile" for you needs. Please uncomment this line:
```
# Need this with release 7.3 / 7.4  since /QIBM/include
#DEFINE=QOAR_INCLUDE_IFS
```
We know that the build process could test for this - but try the above for now.  

The other issue, must be that git did not have permission to create the folder where you tried to clone it to

**Comment by priosoft** [comment]
I had installed noxDB stand alone, and do "make" it work like a charm, everyting ok

instead the make inside ileastic gives error.

I compared two make inside folder noxDB and it seems different, maybe also files inside forder are too.

I had find the compiler command of program that gives error and i tried on 5250 command line and look the joblog, i let you see below, it seams an copy / include error ( I report just one but are more than one)

also the uncommenting DEFINE=QOAR_INCLUDE_IFS doesn't work

I think this project is one of the best I ever see and I'm looking foreward to try it soon

Thank's a lot

CRTCMOD MODULE(ILEASTIC/utl100)                     
SRCSTMF('/prj/ILEastic/noxDB/src/ext/utl100.c')     
OPTIMIZE(10)                                        
ENUM(*INT)                                          
TERASPACE(*YES)                                     
STGMDL(*INHERIT)                                    
SYSIFCOPT(*IFSIO)                                   
INCDIR('/QIBM/include' 'headers/' 'headers/ext/')   
DBGVIEW(*ALL)                                       
DEFINE()
TGTCCSID(1144)                                      
TGTRLS(*CURRENT)                                    


ID messaggio . . . . . :   CZM1003       Gravità  . . . . . . . :   30        
Tipo di messaggio  . . :   Diagnostica                                        
Data invio . . . . . . :   18/10/22      Ora invio  . . . . . . :   17:10:15  
                                                                              
Messaggio . . . :   /prj/ILEastic/noxDB/src/ext/utl100.c, 21.10: CZM0296(30)  
  File #include "ostypes.h" non trovato.                                      
Causa . . . . . :   Non è possibile trovare il file specificato nella         
  direttiva #include. Consultare il C/C++ Language Reference per un ordine di 
  ricerca del file.                                                           
Correzione . . :   Assicurarsi che il percorso di ricerca e il nome file      
  #include siano corretti.

**Comment by NielsLiisberg** [comment]
It must be something with the CCSID  - the ostypes.h is extremely essential
- with this missing nothing works.
We can do a TeamView session tomorrow so I can help you - if you like

**Comment by priosoft** [comment]
Wonderfull.!!

 

I will pay you for the assistance with paypal

 

Really great.!!

 

Is very kind from you.

 

Da: Niels Liisberg ***@***.***> 
Inviato: mercoledì 19 ottobre 2022 16:51
A: sitemule/sitemule.github.io ***@***.***>
Cc: priosoft ***@***.***>; Author ***@***.***>
Oggetto: Re: [sitemule/sitemule.github.io] Issue on gmake (Issue #1)

 

It must be something with the CCSID - the ostypes.h is extremely essential
- with this missing nothing works.
We can do a TeamView session tomorrow so I can help you - if you like

**Comment by NielsLiisberg** [comment]
No problem! You don’t have to pay anything. You are already investing time
in this project- and that’s enough!

I’ll send you a teamView link tomorrow

ons. 19. okt. 2022 kl. 17.00 skrev priosoft ***@***.***>:

**Comment by priosoft** [comment]
Great Niels.!!

 

Da: Niels Liisberg ***@***.***> 
Inviato: mercoledì 19 ottobre 2022 20:47
A: sitemule/sitemule.github.io ***@***.***>
Cc: priosoft ***@***.***>; Author ***@***.***>
Oggetto: Re: [sitemule/sitemule.github.io] Issue on gmake (Issue #1)

 

No problem! You don’t have to pay anything. You are already investing time
in this project- and that’s enough!

I’ll send you a teamView link tomorrow

ons. 19. okt. 2022 kl. 17.00 skrev priosoft ***@***.*** <mailto:***@***.***> >:

**Comment by NielsLiisberg** [comment]
All set
